package order;

public enum OrderType
{
  MARKET_ORDER,
  LIMIT_ORDER,
  STOP_LOSS,
  STOP_LIMIT,
  TRAILING_STOP_LOSS,
  TRAILING_STOP_LOSS_PERCENTAGE,
  TRAILING_STOP_LIMIT,
  TRAILING_STOP_LIMIT_PERCENTAGE
}
